# Generated by Django 5.2.11 on 2026-03-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='email',
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
