# Generated by Django 5.2.11 on 2026-04-09 12:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_bolo_evento_formulario_patrocinadores_delete_medico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('A', 'Agendada'), ('X', 'Cancelada'), ('C', 'Confirmada'), ('R', 'Realizada-')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('criacao_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefone', models.CharField(max_length=15)),
                ('crm', models.CharField(max_length=6)),
                ('especialidades', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('mensagem', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, upload_to='img/%Y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=11)),
                ('criacao_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('mensagem', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, upload_to='img/%Y/%m')),
            ],
        ),
        migrations.DeleteModel(
            name='Bolo',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
        migrations.DeleteModel(
            name='Patrocinadores',
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.medico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.pacientes'),
        ),
    ]
